<?php
declare(strict_types=1);
namespace App\Models;
use PDO;
use App\Core\Authorization;

final class Associado {
    public function __construct(private PDO $db, private Authorization $authorization) {}

    public function allForUser(int $userId, ?string $search=null): array {
        $filter=$this->authorization->associateFilter($userId,'a.Id');
        $sql="SELECT DISTINCT a.Id,a.NumeroAssociado AS Numero,p.Nome,a.DataNascimento,a.Genero,a.NumeroDocumentoIdentificacao,a.NumeroCartaoUtente,a.DataInscricao,a.Activo,n.Nacionalidade,ec.Designacao AS EstadoCivil,cr.Designacao AS ConfissaoReligiosa,td.Designacao AS TipoDocumento,s.Designacao AS Seccao, CASE WHEN a.Genero='M' THEN s.NominativoMasculino WHEN a.Genero='F' THEN s.NominativoFeminino WHEN a.Genero='O' THEN a.NominativoOutro ELSE s.Designacao END AS Nominativo, GROUP_CONCAT(DISTINCT c.Designacao ORDER BY c.Designacao SEPARATOR ', ') AS Companhias FROM associados a INNER JOIN pessoas p ON p.Id=a.IdPessoa LEFT JOIN nacionalidades n ON n.Id=a.IdNacionalidade LEFT JOIN estados_civis ec ON ec.Id=a.IdEstadoCivil LEFT JOIN confissoes_religiosas cr ON cr.Id=a.IdConfissaoReligiosa LEFT JOIN tipos_documento_identificacao td ON td.Id=a.IdTipoDocumentoIdentificacao LEFT JOIN associados_seccoes ase ON ase.IdAssociado=a.Id AND ase.Activo=1 AND ase.DataFim IS NULL LEFT JOIN seccoes s ON s.Id=ase.IdSecao LEFT JOIN associados_companhias ac ON ac.IdAssociado=a.Id AND ac.Activo=1 AND ac.DataFim IS NULL LEFT JOIN companhias c ON c.Id=ac.IdCompanhia WHERE {$filter['sql']}";
        $params=$filter['params'];
        if($search!==''){ $sql.=" AND (p.Nome LIKE ? OR a.NumeroAssociado LIKE ? OR a.NumeroDocumentoIdentificacao LIKE ? OR a.NumeroCartaoUtente LIKE ?)"; $t='%'.$search.'%'; array_push($params,$t,$t,$t,$t); }
        $sql.=' GROUP BY a.Id ORDER BY p.Nome';
        $st=$this->db->prepare($sql); $st->execute($params); return $st->fetchAll();
    }
    public function findForUser(int $uid,int $id): ?array { return $this->authorization->canAccessAssociate($uid,$id)?$this->find($id):null; }
    public function find(int $id): ?array {
        $st=$this->db->prepare("SELECT a.*,p.Nome,n.Nacionalidade,ec.Designacao EstadoCivil,cr.Designacao ConfissaoReligiosa,td.Designacao TipoDocumento FROM associados a JOIN pessoas p ON p.Id=a.IdPessoa LEFT JOIN nacionalidades n ON n.Id=a.IdNacionalidade LEFT JOIN estados_civis ec ON ec.Id=a.IdEstadoCivil LEFT JOIN confissoes_religiosas cr ON cr.Id=a.IdConfissaoReligiosa LEFT JOIN tipos_documento_identificacao td ON td.Id=a.IdTipoDocumentoIdentificacao WHERE a.Id=:id"); $st->execute(['id'=>$id]); return $st->fetch()?:null;
    }
    private function validDate(string $v,string $field,bool $past=true): string { $d=\DateTime::createFromFormat('!Y-m-d',$v); if(!$d||$d->format('Y-m-d')!==$v) throw new \RuntimeException("$field inválida."); if($past && $d>new \DateTime('today')) throw new \RuntimeException("$field não pode ser posterior à data actual."); return $v; }
    private function validate(array $d): void { if(trim((string)($d['Nome']??''))==='') throw new \RuntimeException('O nome é obrigatório.'); $this->validDate((string)($d['DataNascimento']??''),'A data de nascimento'); if(!in_array(($d['Genero']??''),['M','F','O'],true)) throw new \RuntimeException('O género é obrigatório.'); if(($d['Genero']??'')==='O' && trim((string)($d['NominativoOutro']??''))==='') throw new \RuntimeException('O nominativo é obrigatório quando o género é Outro.'); if(!empty($d['NumeroCartaoUtente']) && !preg_match('/^[0-9]{9}$/',(string)$d['NumeroCartaoUtente'])) throw new \RuntimeException('O número do Cartão de Utente deve ter exactamente 9 algarismos.'); }
    public function create(int $uid,array $d,int $companyId,int $sectionId): int {
        if($companyId>0&&!$this->authorization->canManageAssociatesInCompany($uid,$companyId)) throw new \RuntimeException('Não tem permissão para criar associados nessa companhia.'); if($sectionId<=0) throw new \RuntimeException('É obrigatório indicar a secção.'); $this->validate($d); $ins=$this->validDate((string)$d['DataInscricao'],'A data de inscrição');
        $this->db->beginTransaction(); try { $n=(int)$this->db->query('SELECT COALESCE(MAX(CAST(NumeroAssociado AS UNSIGNED)),0)+1 FROM associados FOR UPDATE')->fetchColumn(); $numero=str_pad((string)$n,5,'0',STR_PAD_LEFT); $st=$this->db->prepare('INSERT INTO pessoas (Nome) VALUES (:n)');$st->execute(['n'=>trim($d['Nome'])]);$pid=(int)$this->db->lastInsertId(); $st=$this->db->prepare('INSERT INTO associados (IdPessoa,NumeroAssociado,DataNascimento,Genero,IdNacionalidade,IdEstadoCivil,IdConfissaoReligiosa,IdTipoDocumentoIdentificacao,NumeroDocumentoIdentificacao,NumeroCartaoUtente,NominativoOutro,NomePai,NomeMae,DataInscricao,Activo) VALUES (:p,:num,:dn,:g,:nat,:ec,:cr,:td,:ndi,:cu,:no,:pai,:mae,:di,1)'); $st->execute(['p'=>$pid,'num'=>$numero,'dn'=>$d['DataNascimento'],'g'=>$d['Genero'],'nat'=>$this->nullableInt($d['IdNacionalidade']??null),'ec'=>$this->nullableInt($d['IdEstadoCivil']??null),'cr'=>$this->nullableInt($d['IdConfissaoReligiosa']??null),'td'=>$this->nullableInt($d['IdTipoDocumentoIdentificacao']??null),'ndi'=>$this->nullstr($d['NumeroDocumentoIdentificacao']??null),'cu'=>$this->nullstr($d['NumeroCartaoUtente']??null),'no'=>($d['Genero']==='O'?$this->nullstr($d['NominativoOutro']??null):null),'pai'=>$this->nullstr($d['NomePai']??null),'mae'=>$this->nullstr($d['NomeMae']??null),'di'=>$ins]); $id=(int)$this->db->lastInsertId(); if($companyId>0){$x=$this->db->prepare('INSERT INTO associados_companhias (IdAssociado,IdCompanhia,DataInicio,DataFim,Activo) VALUES (:a,:c,:d,NULL,1)');$x->execute(['a'=>$id,'c'=>$companyId,'d'=>$ins]);} $x=$this->db->prepare('INSERT INTO associados_seccoes (IdAssociado,IdSecao,DataInicio,DataFim,Activo) VALUES (:a,:s,:d,NULL,1)');$x->execute(['a'=>$id,'s'=>$sectionId,'d'=>$ins]); $t=$this->db->prepare('SELECT Id FROM tipos_evento WHERE Designacao=:d LIMIT 1');$t->execute(['d'=>'Admissão']);$tid=$t->fetchColumn(); if($tid!==false){$e=$this->db->prepare('INSERT INTO eventos_associados (IdAssociado,IdTipoEvento,DataEvento,Observacoes) VALUES (:a,:t,:d,:o)');$e->execute(['a'=>$id,'t'=>$tid,'d'=>$ins,'o'=>'Admissão do associado.']);} $this->db->commit();return $id;}catch(\Throwable $e){$this->db->rollBack();throw $e;}
    }
    private function nullableInt($v): ?int { $v=(int)$v; return $v>0?$v:null; } private function nullstr($v): ?string { $v=trim((string)$v);return $v===''?null:$v; }
    public function update(int $uid,int $id,array $d): void { if(!$this->authorization->canAccessAssociate($uid,$id)) throw new \RuntimeException('Não tem permissão para alterar este associado.'); $this->validate($d); $a=$this->find($id); if(!$a) throw new \RuntimeException('Associado não encontrado.'); $this->db->beginTransaction();try{$this->db->prepare('UPDATE pessoas SET Nome=:n WHERE Id=:id')->execute(['n'=>trim($d['Nome']),'id'=>$a['IdPessoa']]);$st=$this->db->prepare('UPDATE associados SET DataNascimento=:dn,Genero=:g,IdNacionalidade=:nat,IdEstadoCivil=:ec,IdConfissaoReligiosa=:cr,IdTipoDocumentoIdentificacao=:td,NumeroDocumentoIdentificacao=:ndi,NumeroCartaoUtente=:cu,NominativoOutro=:no,NomePai=:pai,NomeMae=:mae WHERE Id=:id');$st->execute(['dn'=>$d['DataNascimento'],'g'=>$d['Genero'],'nat'=>$this->nullableInt($d['IdNacionalidade']??null),'ec'=>$this->nullableInt($d['IdEstadoCivil']??null),'cr'=>$this->nullableInt($d['IdConfissaoReligiosa']??null),'td'=>$this->nullableInt($d['IdTipoDocumentoIdentificacao']??null),'ndi'=>$this->nullstr($d['NumeroDocumentoIdentificacao']??null),'cu'=>$this->nullstr($d['NumeroCartaoUtente']??null),'no'=>($d['Genero']==='O'?$this->nullstr($d['NominativoOutro']??null):null),'pai'=>$this->nullstr($d['NomePai']??null),'mae'=>$this->nullstr($d['NomeMae']??null),'id'=>$id]);$this->db->commit();}catch(\Throwable $e){$this->db->rollBack();throw $e;}}
    public function sections(): array{return $this->db->query('SELECT Id,Designacao,NominativoMasculino,NominativoFeminino FROM seccoes ORDER BY Id')->fetchAll();}
    public function currentSection(int $id): ?array{$st=$this->db->prepare("SELECT s.*,CASE WHEN a.Genero='M' THEN s.NominativoMasculino WHEN a.Genero='F' THEN s.NominativoFeminino ELSE a.NominativoOutro END Nominativo FROM associados_seccoes x JOIN seccoes s ON s.Id=x.IdSecao JOIN associados a ON a.Id=x.IdAssociado WHERE x.IdAssociado=:id AND x.Activo=1 AND x.DataFim IS NULL ORDER BY x.Id DESC LIMIT 1");$st->execute(['id'=>$id]);return $st->fetch()?:null;}
    public function sectionHistory(int $uid,int $id): array{$st=$this->db->prepare('SELECT x.*,s.Designacao FROM associados_seccoes x JOIN seccoes s ON s.Id=x.IdSecao WHERE x.IdAssociado=:id ORDER BY x.DataInicio DESC');$st->execute(['id'=>$id]);return $st->fetchAll();}
}
